---
# tasks file for restic
- name: Ensure restic is installed.
  become: true
  ansible.builtin.dnf:
    name: restic
    state: present

- name: Check if repository exists.
  ansible.builtin.stat:
    path: "{{ restic_dir }}/{{ restic_repo_name }}"
  register: out_repo

- name: Attempt to initialize a repository.
  when: not out_repo.stat.exists
  block:
    - name: Ensure backup directory exists.
      become: true
      ansible.builtin.file:
        path: "{{ restic_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Ensure a password file exists.
      ansible.builtin.copy:
        content: "{{ restic_password }}"
        dest: "{{ restic_password_file }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

    - name: Ensure a restic repository has been initialized.
      ansible.builtin.command:
        cmd: "restic init"
      register: out_init
      changed_when: "'created restic repository' in out_init.stdout"
      environment:
        RESTIC_REPOSITORY: "{{ restic_dir }}/{{ restic_repo_name }}"
        RESTIC_PASSWORD_FILE: "{{ restic_password_file }}"
